Bool test programs using mathExpressions
MartinBruun/P4-project pull request #12
Opened 2021-03-19 14:01 UTC by RasmusHoeyerHansen

2021-03-21 11:26 UTC, saxjax commented on OG/Tests/Fixtures/Correct programs/boolExpressions.og
> +	point p = (a,y);
Jeg tænker at det er en typo:  skal der stå point p = (a,b)

2021-03-21 11:28 UTC, saxjax commented on OG/Tests/Fixtures/Correct programs/boolExpressions.og
> +   	bool test7 = (7^2) + 45 - 34 2 * 4 / (a*b) => 49;
bool test7 = (7^2) + 45 - 34 2 * 4 / (a*b) => 49;

skal der stå 342  eller mangler der en operator?

2021-03-29 07:23 UTC, MartinBruun requested changes
Ser godt ud, har kigget på det lige lidt overfladisk, men vi tager det bare :)

2021-03-29 07:23 UTC, MartinBruun commented on OG/OG/OG.g4
> +endPointAssignment  : id=EndPointReference '=' value=pointReference
Hvor er StartPointReference og EndPointReference defineret?

2021-03-29 07:23 UTC, MartinBruun commented on OG/OG/OG.g4
> +curveCommand    : 'curve''.''withAngle' '('angle=mathExpression ')'  fromCmd=fromCommand toCmd=toCommand;
Kunne det give mening, at Command har en "Type" (line/curve) "Modifiers" (angle/mm.) "MovementCommands" (from/to)?

Så det bliver i den semantiske analyse, at vores TypeChecker tilføjer korrekte modifiers (aka. line.withAngle() er semantisk men ikke syntaktisk forkert). Gør det vel nemmere at udvide med andre modifikationer fremmadrettet?

2021-03-29 07:23 UTC, MartinBruun commented on OG/OG/OG.g4
> +                | '.to''(' toPoint=EndPointReference ')'    #toWithEndPointRef
".to" bør opdeles i "." og "to"

Vores problem er dog, at vi ikke kan enforce, at der ikke må være mellemrum mellem ".to" og "("
På samme måde vil denne ændring medfører, at ".  to   (1,    2 )" er syntaktisk valid. Tror dog ikke det er et stort problem.

2021-03-29 07:23 UTC, MartinBruun commented on OG/OG/OG.g4
> +                |  '.from' '(' fromPoint=EndPointReference ')'      #fromWithEndPointRef
".from" -> "." "from"

2021-03-29 07:23 UTC, MartinBruun commented on OG/OG/OG.g4
> +                | 'repeat''.''until''(' iterator=boolExpression')' statements=body 'repeat.end'  #untilCondition
Kan man overveje, at repeat.until(VAL) tager en VAL, som hvis den er et tal er det en numberIteration mens hvis det er en bool, er det en untilIteration?

Synes bare det er mærkeligt, at repeat() og repeat.until() er lidt forvirrende med placeringen af (), hvorimod repeat.until(5) vel er tydeligt nok, at jeg repeater "indtil" der er gået 5 gange?

2021-03-29 07:23 UTC, MartinBruun commented on OG/OG/OG.g4
> +
Har vi behov for void funcs? Eller er vores shapes i virkeligheden vores "void funktioner"?
Hvad skulle de bruges til? :)

(Plus det er liiiidt c agtigt, men det går nok xD)

2021-03-29 07:23 UTC, MartinBruun commented on OG/OG/OG.g4
> +            |                                                #noParameter
Hvorfor hedder den "firstParameter"? Burde "currentParameter" ikke være mere sigende?

Ellers er det jo function something(firstParameter, firstParameter, firstParameter... params)?

2021-03-29 08:57 UTC, merged