Add functions and shapes
MartinBruun/P4-project pull request #6
Opened 2021-03-19 12:29 UTC by MartinBruun

2021-03-19 12:38 UTC, basilbees approved these changes
looks great

2021-03-21 11:31 UTC, saxjax commented on OG/Tests/Fixtures/nested_shape.og
> +    shape nestedShape {
nested declaration af shapes var vist ikke ok?

2021-03-21 11:32 UTC, saxjax requested changes

2021-03-21 11:32 UTC, saxjax commented on OG/Tests/Fixtures/nested_shape.og
> +
nested declaration af shapes var vist ikke ok?

2021-03-26 11:47 UTC, esindb17 approved these changes

2021-03-26 11:48 UTC, esindb17 approved these changes

2021-03-26 13:11 UTC, merged